In [ ]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Function to generate rotation matrix around x-axis
def rotation_matrix_x(theta):
    R_x = np.array([[1, 0, 0],
                    [0, np.cos(theta), -np.sin(theta)],
                    [0, np.sin(theta), np.cos(theta)]])
    return R_x

# Function to generate rotation matrix around y-axis
def rotation_matrix_y(theta):
    R_y = np.array([[np.cos(theta), 0, np.sin(theta)],
                    [0, 1, 0],
                    [-np.sin(theta), 0, np.cos(theta)]])
    return R_y

# Function to generate rotation matrix around z-axis
def rotation_matrix_z(theta):
    R_z = np.array([[np.cos(theta), -np.sin(theta), 0],
                    [np.sin(theta), np.cos(theta), 0],
                    [0, 0, 1]])
    return R_z

# Verify properties of rotation matrices
def verify_rotation_matrix(R):
    # Determinant should be 1
    determinant = np.linalg.det(R)
    print("Determinant:", determinant)

    # Inverse should be equal to transpose
    inverse = np.linalg.inv(R)
    transpose = R.T
    print("Inverse:")
    print(inverse)
    print("Transpose:")
    print(transpose)

print("Rotation matrix around x-axis:")
print(R_x)
verify_rotation_matrix(R_x)

print("\nRotation matrix around y-axis:")
print(R_y)
verify_rotation_matrix(R_y)

print("\nRotation matrix around z-axis:")
print(R_z)
verify_rotation_matrix(R_z)

Rotation matrix around x-axis:
[[ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]
 [ 0.          0.70710678  0.70710678]]
Determinant: 1.0
Inverse:
[[ 1.          0.          0.        ]
 [ 0.          0.70710678  0.70710678]
 [ 0.         -0.70710678  0.70710678]]
Transpose:
[[ 1.          0.          0.        ]
 [ 0.          0.70710678  0.70710678]
 [ 0.         -0.70710678  0.70710678]]

Rotation matrix around y-axis:
[[ 0.8660254  0.         0.5      ]
 [ 0.         1.         0.       ]
 [-0.5        0.         0.8660254]]
Determinant: 1.0
Inverse:
[[ 0.8660254  0.        -0.5      ]
 [ 0.         1.         0.       ]
 [ 0.5        0.         0.8660254]]
Transpose:
[[ 0.8660254  0.        -0.5      ]
 [ 0.         1.         0.       ]
 [ 0.5        0.         0.8660254]]

Rotation matrix around z-axis:
[[ 0.5       -0.8660254  0.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.         0.         1.       ]]
Determinant: 1.0
Inverse:
[[ 0.5        0

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Function to generate rotation matrix around x-axis
def rotation_matrix_x(theta):
    R_x = np.array([[1, 0, 0],
                    [0, np.cos(theta), -np.sin(theta)],
                    [0, np.sin(theta), np.cos(theta)]])
    return R_x

# Function to generate rotation matrix around y-axis
def rotation_matrix_y(theta):
    R_y = np.array([[np.cos(theta), 0, np.sin(theta)],
                    [0, 1, 0],
                    [-np.sin(theta), 0, np.cos(theta)]])
    return R_y

# Function to generate rotation matrix around z-axis
def rotation_matrix_z(theta):
    R_z = np.array([[np.cos(theta), -np.sin(theta), 0],
                    [np.sin(theta), np.cos(theta), 0],
                    [0, 0, 1]])
    return R_z

# Function to combine multiple rotation matrices
def combine_rotations(rotations):
    combined_rotation = np.array([[1, 0, 0],
                        [0, 1, 0],
                        [0, 0, 1]])
    for rotation in rotations:
        combined_rotation = np.dot(rotation, combined_rotation)
    return combined_rotation

# Visualization
def plot_rotation(R, title):
    # Create unit vectors along axes
    vectors = np.array([[1, 0, 0],
                        [0, 1, 0],
                        [0, 0, 1]])

    # Apply rotation000000000
    rotated_vectors = np.dot(R, vectors.T).T

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.quiver(0, 0, 0, rotated_vectors[:,0], rotated_vectors[:,1], rotated_vectors[:,2], color='r')
    ax.set_xlim([-1, 1])
    ax.set_ylim([-1, 1])
    ax.set_zlim([-1, 1])
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    ax.set_title(title)
    plt.show()

# Example usage
theta_x = np.pi/4  # 45 degrees rotation around x-axis
theta_y = np.pi/6  # 30 degrees rotation around y-axis
theta_z = np.pi/3  # 60 degrees rotation around z-axis

R_x = rotation_matrix_x(theta_x)
R_y = rotation_matrix_y(theta_y)
R_z = rotation_matrix_z(theta_z)

# Combine rotations
combined_rotation = combine_rotations([R_x, R_y, R_z])

# Visualize the combined rotation
plot_rotation(combined_rotation, 'Combined Rotation')

In [ ]:
import math

def inverse_kinematics(x, y, l1, l2):

    # Compute the distance to the target point
    distance = math.sqrt(x**2 + y**2)

    # Check if the target point is reachable
    if distance > l1 + l2:
      return None  # The point is outside the reach of the arm

    # Calculate the angle for the second joint using the law of cosines
    cos_theta2 = (distance**2 - l1**2 - l2**2) / (2 * l1 * l2)
    theta2 = math.acos(cos_theta2)

    # Calculate the angle for the first joint
    k1 = l1 + l2 * cos_theta2
    k2 = l2 * math.sin(theta2)
    theta1 = math.atan2(y, x) - math.atan2(k2, k1)

    # Convert angles to degrees
    # theta1 = math.degrees(theta1)
    # theta2 = math.degrees(theta2)
    return (theta1, theta2)


# Example usage:
l1 = 1.0  # Length of the first link
l2 = 1.0  # Length of the second link
x_target = 1.5  # x-coordinate of the target
y_target = 0.5  # y-coordinate of the target


angles = inverse_kinematics(x_target, y_target, l1, l2)

if angles:
    print("Theta1: {:.2f} Degrees, Theta2: {:.2f} Degrees".format(*angles))

else:
    print("The target point is unreachable.")

Theta1: -0.34 Degrees, Theta2: 1.32 Degrees


In [ ]:
'''
# Visualization
def plot_rotation(axis, R, title):
    # base frame (frame 0)(rotauion of frame i relative to frame zero)
    vectors = np.array([[1, 0, 0],
                        [0, 1, 0],
                        [0, 0, 1]])

    # Apply rotation
    rotated_vectors = np.dot(R, vectors.T).T

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.quiver(0, 0, 0, rotated_vectors[:,0], rotated_vectors[:,1], rotated_vectors[:,2], color='r')#ax.quiver(0, 0, 0, rotated_vectors[:,0], rotated_vectors[:,1], rotated_vectors[:,2], color='r') plots the 3D vectors starting from the origin (0, 0, 0) with their components given by rotated_vectors[:,0], rotated_vectors[:,1], and rotated_vectors[:,2], and the color of the vectors is red.
    ax.set_xlim([-1, 1])
    ax.set_ylim([-1, 1])
    ax.set_zlim([-1, 1])
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    ax.set_title(title)
    plt.show()

# Example usage
theta = np.pi/4  # 45 degrees
R_x = rotation_matrix_x(theta)
R_y = rotation_matrix_y(theta)
R_z = rotation_matrix_z(theta)

print("Rotation matrix around x-axis:")
print(R_x)
verify_rotation_matrix(R_x)
plot_rotation('x', R_x, 'Rotation around x-axis')

print("\nRotation matrix around y-axis:")
print(R_y)
verify_rotation_matrix(R_y)
plot_rotation('y', R_y, 'Rotation around y-axis')

print("\nRotation matrix around z-axis:")
print(R_z)
verify_rotation_matrix(R_z)
plot_rotation('z', R_z, 'Rotation around z-axis')
'''

'\n# Visualization\ndef plot_rotation(axis, R, title):\n    # base frame (frame 0)(rotauion of frame i relative to frame zero)\n    vectors = np.array([[1, 0, 0],\n                        [0, 1, 0],\n                        [0, 0, 1]])\n\n    # Apply rotation\n    rotated_vectors = np.dot(R, vectors.T).T\n\n    fig = plt.figure()\n    ax = fig.add_subplot(111, projection=\'3d\')\n    ax.quiver(0, 0, 0, rotated_vectors[:,0], rotated_vectors[:,1], rotated_vectors[:,2], color=\'r\')#ax.quiver(0, 0, 0, rotated_vectors[:,0], rotated_vectors[:,1], rotated_vectors[:,2], color=\'r\') plots the 3D vectors starting from the origin (0, 0, 0) with their components given by rotated_vectors[:,0], rotated_vectors[:,1], and rotated_vectors[:,2], and the color of the vectors is red.\n    ax.set_xlim([-1, 1])\n    ax.set_ylim([-1, 1])\n    ax.set_zlim([-1, 1])\n    ax.set_xlabel(\'X\')\n    ax.set_ylabel(\'Y\')\n    ax.set_zlabel(\'Z\')\n    ax.set_title(title)\n    plt.show()\n\n# Example usage\ntheta 